### ISSUE TITLE
need fix like bilateral/retines

### ISSUE THREAD

**Issue by sl1pkn07** [HomeOfVapourSynthEvolution/VapourSynth-BM3D#10]
Hi

BM3D configure needs fix like HomeOfVapourSynthEvolution/VapourSynth-Bilateral@87eac7a

greetings

**Comment by mawen1250** [comment]
Thanks for the report and PR, should these lines be modified?
from
```
if cc_check "-O2 -ffast-math $CXXFLAGS" "$LDFLAGS"; then
    CXXFLAGS="-O2 -ffast-math $CXXFLAGS"
fi
if cc_check "$CXXFLAGS -mfpmath=sse" "$LDFLAGS"; then
    CXXFLAGS="$CXXFLAGS -mfpmath=sse"
fi
```
to
```
if cc_check "-Os -ffast-math $CXXFLAGS" "$LDFLAGS"; then
    CXXFLAGS="-Os -ffast-math $CXXFLAGS"
fi
if cc_check "$CXXFLAGS" "$LDFLAGS"; then
    CXXFLAGS="$CXXFLAGS"
fi
```

**Comment by sl1pkn07** [comment]
mm you can remove the -mfpmath=sse if you need it, but if can, keeping the '-O2'. i think is better keep the speed instead of the reduction of size of the binary. i'm not sure in this case which is better

**Comment by mawen1250** [comment]
Thanks, done https://github.com/HomeOfVapourSynthEvolution/VapourSynth-BM3D/commit/cf5bcee0ba4cac772df951191915e46789fcabfc
