### ISSUE TITLE
Source does not compile with gcc-5 on Linux

### ISSUE THREAD

**Issue by 4re** [HomeOfVapourSynthEvolution/VapourSynth-BM3D#14]
Many errors since latest commits from recent days using gcc-5.2 on Linux: http://pastebin.com/fApmHkui

**Comment by mawen1250** [comment]
Should be fixed now https://github.com/HomeOfVapourSynthEvolution/VapourSynth-BM3D/commit/2f6b9cc3cf6e6015a165072ae3c337c3baf1d617

**Comment by 4re** [comment]
Yup. :)
