### ISSUE TITLE
Artifact with some video

### ISSUE THREAD

**Issue by MonoS** [HomeOfVapourSynthEvolution/VapourSynth-BM3D#20]
Hi, as i said [on Doom9](http://forum.doom9.org/showthread.php?p=1782207#post1782207) i've got some strange artifact with [this script](http://pastebin.com/wm6h4gSm) on [this video](https://mega.nz/#!b14RDa6Z!82LdVsl0S4lfMJ5s7YH2pahJqFZSHvRjKk1sDqDiQ9U)

The artifact can be seen at [frame 648](https://abload.de/img/artifactgvq1k.png), the black lines around the eyes, [the screen was made with the last lines uncommented], also the more the luma sigma the more the artifact is visible.

Thanks for the attention.

**Comment by mawen1250** [comment]
Did some tests on this script.
I found that the dynamic range of clip "ref" is different, which caused your problem.

Just change line 29 to:
ref = core.fmtc.bitdepth(ref, flt=True, fulls=True)
which treat it (of OPP) as full range input.

**Comment by MonoS** [comment]
My apologies for reporting about this problem here, I'd never have expected a problem like a wrong range in pixels with "average" values.

Thanks a lot for your help.

**Comment by RoyiAvital** [comment]
Is this closed issue?

**Comment by MonoS** [comment]
Yes, it is, my apologies for not have marked this before.

**Comment by RoyiAvital** [comment]
@MonoS, Do you know if @mawen1250 is still active?
Haven't seen him for 2 months now.

**Comment by MonoS** [comment]
I don't know, i'm sorry.

**Comment by invisiblearts** [comment]
@RoyiAvital AFAIK he should be busy recently, and might not be active as before till as long as about a year later.

**Comment by RoyiAvital** [comment]
@invisiblearts , I see,
I just couldn't contact him in any way and wanted to make sure he's OK.

Just was worried about him and wanted to know if there is anything to assist with.

Happy to hear he's OK.

Thank You.

**Comment by msg7086** [comment]
@RoyiAvital I believe he's busy in school life right now.

**Comment by RoyiAvital** [comment]
I see.
Hopefully we'll have a sign of life in the Semester Break.

Thank You.

**Comment by RoyiAvital** [comment]
Hi,

Any news on @mawen1250?
I need to send him something he owns and I can't get a hold of him.

Thank You.

**Comment by RoyiAvital** [comment]
@invisiblearts , @msg7086 , 
I still can't in touch with @mawen1250 .
Is he OK?
I'm really worried.

We have been in touch and suddenly he disappeared.

Is there a way to send him a message?
Maybe through you guys?

Thank You.

**Comment by RoyiAvital** [comment]
@msg7086 , @invisiblearts , @MonoS , @mawen1250 , Is there a way to contact any of you on mail?
It's really important.

Thank You.

**Comment by MonoS** [comment]
@RoyiAvital you can contact me, but it depends on what you need to ask me

**Comment by RoyiAvital** [comment]
@MonoS ,
Could you send me an email?
I will tell you all about it.

You can send me at the same user here with Yahoo: `<MyGitHubUserName>@yahoo.com`.

Thank You.
