### ISSUE TITLE
Will there be OpenCL or CUDA version implementation of BM3D？

### ISSUE THREAD

**Issue by capric98** [HomeOfVapourSynthEvolution/VapourSynth-BM3D#23]
BM3D is a great algorithm in denoising with a bit of speed tradeoff. 
I also noticed that there are some implementations of GPU accelerated BM3D. With ignorance of writing VapourSynth plugins, I just wonder whether it is possible to introduce GPU acceleration in this plugin or not.

**Comment by NSQY** [comment]
https://github.com/WolframRhodium/VapourSynth-BM3DCUDA

**Comment by capric98** [comment]
> https://github.com/WolframRhodium/VapourSynth-BM3DCUDA

Thanks a lot!
