### ISSUE TITLE
fail build 33ffe33

### ISSUE THREAD

**Issue by sl1pkn07** [HomeOfVapourSynthEvolution/VapourSynth-BM3D#6]
hi

fail build commit 33ffe332e430f5017f06d12630683ba910b4233a

http://sl1pkn07.wtf/paste/view/48c6369e

gcc5 related?

greetings

**Comment by mawen1250** [comment]
Thanks for the report
It should be fixed now https://github.com/HomeOfVapourSynthEvolution/VapourSynth-BM3D/commit/d50b361af00ff9372950adf5a9b8548d7c3582b0
