### ISSUE TITLE
Don't link against libvapoursynth

### ISSUE THREAD

**Issue by darealshinji** [HomeOfVapourSynthEvolution/VapourSynth-BM3D#8]
VapourSynth plugins don't need to be linked against libvapoursynth.

**Comment by mawen1250** [comment]
merged https://github.com/HomeOfVapourSynthEvolution/VapourSynth-BM3D/commit/f71979a4e711205d4a6082839375da1638a063a9

**Comment by darealshinji** [comment]
You can use this code by the way I you still want a separate check for VapourSynth headers: https://github.com/dwbuiten/d2vsource/commit/514d5f3683a397ee36aae23cb30a827fdbda0825

**Comment by mawen1250** [comment]
added https://github.com/HomeOfVapourSynthEvolution/VapourSynth-BM3D/commit/0ab7e44962c26a6f75263f6a4f4254999ec3122a
